<a href="https://colab.research.google.com/github/nahK994/TransferLearningStuffs/blob/master/first_day.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as sp
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

#scalar
scalar = torch.tensor(7)
print("# Scalar")
print(scalar)
print(f"ndim -> {scalar.ndim}")
print(f"item -> {scalar.item()}")
print()

#vector
print("# Vector")
vector = torch.tensor([7, 7])
print(vector)
print(f"ndim -> {vector.ndim}")
print(f"shape -> {vector.shape}")
print()

#MATRIX
print("# Matrix")
matrix = torch.tensor([[7, 8, 9, 10], [11, 12, 13, 14], [15, 16, 17, 18]])
print(matrix)
print(f"ndim -> {matrix.ndim}")
print(f"shape -> {matrix.shape}")
print()

#TENSOR
print("# Tensor")
tensor = torch.tensor([
    [
      [7, 8, 9, 10],
      [11, 12, 13, 14],
      [15, 16, 17, 18]
    ]
])
print(tensor)
print(f"ndim -> {tensor.ndim}")
print(f"shape -> {matrix.shape}")
print()

2.3.1+cu121
# Scalar
tensor(7)
ndim -> 0
item -> 7

# Vector
tensor([7, 7])
ndim -> 1
shape -> torch.Size([2])

# Matrix
tensor([[ 7,  8,  9, 10],
        [11, 12, 13, 14],
        [15, 16, 17, 18]])
ndim -> 2
shape -> torch.Size([3, 4])

# Tensor
tensor([[[ 7,  8,  9, 10],
         [11, 12, 13, 14],
         [15, 16, 17, 18]]])
ndim -> 3
shape -> torch.Size([3, 4])

