<a href="https://colab.research.google.com/github/nahK994/TransferLearningStuffs/blob/master/first_day.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import numpy as sp
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

#scalar
scalar = torch.tensor(7)
print("# Scalar")
print(scalar)
print(f"Scalar ndim -> {scalar.ndim}")
print(f"Scalar shape -> {scalar.shape}")
print(f"Scalar item -> {scalar.item()}")
print()

#vector
print("# Vector")
vector = torch.tensor([7, 7])
print(vector)
print(f"Vector ndim -> {vector.ndim}")
print(f"Vector shape -> {vector.shape}")
print()

#MATRIX
print("# Matrix")
matrix = torch.tensor([[7, 8, 9, 10], [11, 12, 13, 14], [15, 16, 17, 18]])
print(matrix)
print(f"Matrix ndim -> {matrix.ndim}")
print(f"Matrix shape -> {matrix.shape}")
print()

#TENSOR
print("# Tensor")
tensor = torch.tensor([
    [
      [7, 8, 9, 10],
      [11, 12, 13, 14],
      [15, 16, 17, 18]
    ],
    [
      [7, 8, 9, 10],
      [11, 12, 13, 14],
      [15, 16, 17, 18]
    ]
])
print(tensor)
print(f"Tensor ndim -> {tensor.ndim}")
print(f"Tensor shape -> {tensor.shape}")
print()

print("# Random tensor")
random_tensor = torch.rand(size=(3, 4, 5))
print(random_tensor)
print(f"Random tensor ndim -> {random_tensor.ndim}")
print(f"Random tensor shape -> {random_tensor.shape}")
print()

print("# All zeros")
zeros = torch.zeros(size=(2, 3, 5))
print(zeros)
print(f"zeros ndim -> {zeros.ndim}")
print(f"zeros shape -> {zeros.shape}")
print()

print("# Random ones")
ones = torch.ones(size=(1, 5, 2))
print(ones)
print(f"ones ndim -> {ones.ndim}")
print(f"ones shape -> {ones.shape}")
print()

2.3.1+cu121
# Scalar
tensor(7)
Scalar ndim -> 0
Scalar shape -> torch.Size([])
Scalar item -> 7

# Vector
tensor([7, 7])
Vector ndim -> 1
Vector shape -> torch.Size([2])

# Matrix
tensor([[ 7,  8,  9, 10],
        [11, 12, 13, 14],
        [15, 16, 17, 18]])
Matrix ndim -> 2
Matrix shape -> torch.Size([3, 4])

# Tensor
tensor([[[ 7,  8,  9, 10],
         [11, 12, 13, 14],
         [15, 16, 17, 18]],

        [[ 7,  8,  9, 10],
         [11, 12, 13, 14],
         [15, 16, 17, 18]]])
Tensor ndim -> 3
Tensor shape -> torch.Size([2, 3, 4])

# Random tensor
tensor([[[0.4252, 0.9650, 0.2973, 0.2363, 0.2137],
         [0.5080, 0.3342, 0.7266, 0.9899, 0.0600],
         [0.9055, 0.9121, 0.0704, 0.3533, 0.8539],
         [0.9526, 0.7457, 0.1406, 0.7820, 0.4426]],

        [[0.6067, 0.8174, 0.7551, 0.3734, 0.3004],
         [0.1783, 0.0704, 0.4735, 0.3088, 0.2126],
         [0.4535, 0.6267, 0.5762, 0.7054, 0.0021],
         [0.4703, 0.8133, 0.4514, 0.6303, 0.2524]],

        [[0.5303, 0.5904, 0.2